# Generated by Django 2.1.3 on 2018-12-10 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20181126_0102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='subject',
            new_name='new_subject',
        ),
    ]
