# Generated by Django 2.1.3 on 2018-12-10 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20181210_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='message',
            new_name='new_message',
        ),
    ]
